// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientSessionsColumns holds the columns for the "client_sessions" table.
	ClientSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "user_client_sessions", Type: field.TypeInt},
	}
	// ClientSessionsTable holds the schema information for the "client_sessions" table.
	ClientSessionsTable = &schema.Table{
		Name:       "client_sessions",
		Columns:    ClientSessionsColumns,
		PrimaryKey: []*schema.Column{ClientSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_sessions_users_client_sessions",
				Columns:    []*schema.Column{ClientSessionsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransferCodesColumns holds the columns for the "transfer_codes" table.
	TransferCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "user_transfer_code", Type: field.TypeInt, Unique: true},
	}
	// TransferCodesTable holds the schema information for the "transfer_codes" table.
	TransferCodesTable = &schema.Table{
		Name:       "transfer_codes",
		Columns:    TransferCodesColumns,
		PrimaryKey: []*schema.Column{TransferCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transfer_codes_users_transfer_code",
				Columns:    []*schema.Column{TransferCodesColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientSessionsTable,
		TransferCodesTable,
		UsersTable,
	}
)

func init() {
	ClientSessionsTable.ForeignKeys[0].RefTable = UsersTable
	TransferCodesTable.ForeignKeys[0].RefTable = UsersTable
}
