// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sijiaoh/go-godot-template/api_server/ent/clientsession"
	"github.com/sijiaoh/go-godot-template/api_server/ent/predicate"
)

// ClientSessionDelete is the builder for deleting a ClientSession entity.
type ClientSessionDelete struct {
	config
	hooks    []Hook
	mutation *ClientSessionMutation
}

// Where appends a list predicates to the ClientSessionDelete builder.
func (_d *ClientSessionDelete) Where(ps ...predicate.ClientSession) *ClientSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClientSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClientSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clientsession.Table, sqlgraph.NewFieldSpec(clientsession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClientSessionDeleteOne is the builder for deleting a single ClientSession entity.
type ClientSessionDeleteOne struct {
	_d *ClientSessionDelete
}

// Where appends a list predicates to the ClientSessionDelete builder.
func (_d *ClientSessionDeleteOne) Where(ps ...predicate.ClientSession) *ClientSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClientSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clientsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
