// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sijiaoh/go-godot-template/game_server/ent/transfercode"
	"github.com/sijiaoh/go-godot-template/game_server/ent/user"
)

// TransferCode is the model entity for the TransferCode schema.
type TransferCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransferCodeQuery when eager-loading is set.
	Edges              TransferCodeEdges `json:"edges"`
	user_transfer_code *int
	selectValues       sql.SelectValues
}

// TransferCodeEdges holds the relations/edges for other nodes in the graph.
type TransferCodeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferCodeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransferCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transfercode.FieldID:
			values[i] = new(sql.NullInt64)
		case transfercode.FieldCode:
			values[i] = new(sql.NullString)
		case transfercode.ForeignKeys[0]: // user_transfer_code
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransferCode fields.
func (_m *TransferCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transfercode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case transfercode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case transfercode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_transfer_code", value)
			} else if value.Valid {
				_m.user_transfer_code = new(int)
				*_m.user_transfer_code = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TransferCode.
// This includes values selected through modifiers, order, etc.
func (_m *TransferCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TransferCode entity.
func (_m *TransferCode) QueryUser() *UserQuery {
	return NewTransferCodeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TransferCode.
// Note that you need to call TransferCode.Unwrap() before calling this method if this TransferCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TransferCode) Update() *TransferCodeUpdateOne {
	return NewTransferCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TransferCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TransferCode) Unwrap() *TransferCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransferCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TransferCode) String() string {
	var builder strings.Builder
	builder.WriteString("TransferCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteByte(')')
	return builder.String()
}

// TransferCodes is a parsable slice of TransferCode.
type TransferCodes []*TransferCode
