// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sijiaoh/go-godot-template/game_server/ent/transfercode"
	"github.com/sijiaoh/go-godot-template/game_server/ent/user"
)

// TransferCodeCreate is the builder for creating a TransferCode entity.
type TransferCodeCreate struct {
	config
	mutation *TransferCodeMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *TransferCodeCreate) SetCode(v string) *TransferCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TransferCodeCreate) SetUserID(id int) *TransferCodeCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TransferCodeCreate) SetUser(v *User) *TransferCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TransferCodeMutation object of the builder.
func (_c *TransferCodeCreate) Mutation() *TransferCodeMutation {
	return _c.mutation
}

// Save creates the TransferCode in the database.
func (_c *TransferCodeCreate) Save(ctx context.Context) (*TransferCode, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferCodeCreate) SaveX(ctx context.Context) *TransferCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "TransferCode.code"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TransferCode.user"`)}
	}
	return nil
}

func (_c *TransferCodeCreate) sqlSave(ctx context.Context) (*TransferCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferCodeCreate) createSpec() (*TransferCode, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transfercode.Table, sqlgraph.NewFieldSpec(transfercode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(transfercode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfercode.UserTable,
			Columns: []string{transfercode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_transfer_code = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransferCodeCreateBulk is the builder for creating many TransferCode entities in bulk.
type TransferCodeCreateBulk struct {
	config
	err      error
	builders []*TransferCodeCreate
}

// Save creates the TransferCode entities in the database.
func (_c *TransferCodeCreateBulk) Save(ctx context.Context) ([]*TransferCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferCodeCreateBulk) SaveX(ctx context.Context) []*TransferCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
