// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sijiaoh/go-godot-template/game_server/ent/transfercode"
	"github.com/sijiaoh/go-godot-template/game_server/ent/user"
)

// TransferCodeCreate is the builder for creating a TransferCode entity.
type TransferCodeCreate struct {
	config
	mutation *TransferCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *TransferCodeCreate) SetCode(v string) *TransferCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TransferCodeCreate) SetUserID(id int) *TransferCodeCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TransferCodeCreate) SetUser(v *User) *TransferCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TransferCodeMutation object of the builder.
func (_c *TransferCodeCreate) Mutation() *TransferCodeMutation {
	return _c.mutation
}

// Save creates the TransferCode in the database.
func (_c *TransferCodeCreate) Save(ctx context.Context) (*TransferCode, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferCodeCreate) SaveX(ctx context.Context) *TransferCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "TransferCode.code"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TransferCode.user"`)}
	}
	return nil
}

func (_c *TransferCodeCreate) sqlSave(ctx context.Context) (*TransferCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferCodeCreate) createSpec() (*TransferCode, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transfercode.Table, sqlgraph.NewFieldSpec(transfercode.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(transfercode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfercode.UserTable,
			Columns: []string{transfercode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_transfer_code = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransferCode.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransferCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *TransferCodeCreate) OnConflict(opts ...sql.ConflictOption) *TransferCodeUpsertOne {
	_c.conflict = opts
	return &TransferCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransferCodeCreate) OnConflictColumns(columns ...string) *TransferCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransferCodeUpsertOne{
		create: _c,
	}
}

type (
	// TransferCodeUpsertOne is the builder for "upsert"-ing
	//  one TransferCode node.
	TransferCodeUpsertOne struct {
		create *TransferCodeCreate
	}

	// TransferCodeUpsert is the "OnConflict" setter.
	TransferCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *TransferCodeUpsert) SetCode(v string) *TransferCodeUpsert {
	u.Set(transfercode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TransferCodeUpsert) UpdateCode() *TransferCodeUpsert {
	u.SetExcluded(transfercode.FieldCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TransferCodeUpsertOne) UpdateNewValues() *TransferCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TransferCodeUpsertOne) Ignore() *TransferCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransferCodeUpsertOne) DoNothing() *TransferCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransferCodeCreate.OnConflict
// documentation for more info.
func (u *TransferCodeUpsertOne) Update(set func(*TransferCodeUpsert)) *TransferCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransferCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *TransferCodeUpsertOne) SetCode(v string) *TransferCodeUpsertOne {
	return u.Update(func(s *TransferCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TransferCodeUpsertOne) UpdateCode() *TransferCodeUpsertOne {
	return u.Update(func(s *TransferCodeUpsert) {
		s.UpdateCode()
	})
}

// Exec executes the query.
func (u *TransferCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransferCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransferCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TransferCodeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TransferCodeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TransferCodeCreateBulk is the builder for creating many TransferCode entities in bulk.
type TransferCodeCreateBulk struct {
	config
	err      error
	builders []*TransferCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the TransferCode entities in the database.
func (_c *TransferCodeCreateBulk) Save(ctx context.Context) ([]*TransferCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferCodeCreateBulk) SaveX(ctx context.Context) []*TransferCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransferCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransferCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *TransferCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *TransferCodeUpsertBulk {
	_c.conflict = opts
	return &TransferCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransferCodeCreateBulk) OnConflictColumns(columns ...string) *TransferCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransferCodeUpsertBulk{
		create: _c,
	}
}

// TransferCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of TransferCode nodes.
type TransferCodeUpsertBulk struct {
	create *TransferCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TransferCodeUpsertBulk) UpdateNewValues() *TransferCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransferCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TransferCodeUpsertBulk) Ignore() *TransferCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransferCodeUpsertBulk) DoNothing() *TransferCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransferCodeCreateBulk.OnConflict
// documentation for more info.
func (u *TransferCodeUpsertBulk) Update(set func(*TransferCodeUpsert)) *TransferCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransferCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *TransferCodeUpsertBulk) SetCode(v string) *TransferCodeUpsertBulk {
	return u.Update(func(s *TransferCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TransferCodeUpsertBulk) UpdateCode() *TransferCodeUpsertBulk {
	return u.Update(func(s *TransferCodeUpsert) {
		s.UpdateCode()
	})
}

// Exec executes the query.
func (u *TransferCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TransferCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransferCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransferCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
