// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sijiaoh/go-godot-template/game_server/ent/clientsession"
	"github.com/sijiaoh/go-godot-template/game_server/ent/user"
)

// ClientSessionCreate is the builder for creating a ClientSession entity.
type ClientSessionCreate struct {
	config
	mutation *ClientSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetToken sets the "token" field.
func (_c *ClientSessionCreate) SetToken(v string) *ClientSessionCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ClientSessionCreate) SetUserID(id int) *ClientSessionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ClientSessionCreate) SetUser(v *User) *ClientSessionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ClientSessionMutation object of the builder.
func (_c *ClientSessionCreate) Mutation() *ClientSessionMutation {
	return _c.mutation
}

// Save creates the ClientSession in the database.
func (_c *ClientSessionCreate) Save(ctx context.Context) (*ClientSession, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientSessionCreate) SaveX(ctx context.Context) *ClientSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientSessionCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "ClientSession.token"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ClientSession.user"`)}
	}
	return nil
}

func (_c *ClientSessionCreate) sqlSave(ctx context.Context) (*ClientSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientSessionCreate) createSpec() (*ClientSession, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientsession.Table, sqlgraph.NewFieldSpec(clientsession.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(clientsession.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientsession.UserTable,
			Columns: []string{clientsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_client_sessions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ClientSession.Create().
//		SetToken(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClientSessionUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ClientSessionCreate) OnConflict(opts ...sql.ConflictOption) *ClientSessionUpsertOne {
	_c.conflict = opts
	return &ClientSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClientSessionCreate) OnConflictColumns(columns ...string) *ClientSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClientSessionUpsertOne{
		create: _c,
	}
}

type (
	// ClientSessionUpsertOne is the builder for "upsert"-ing
	//  one ClientSession node.
	ClientSessionUpsertOne struct {
		create *ClientSessionCreate
	}

	// ClientSessionUpsert is the "OnConflict" setter.
	ClientSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetToken sets the "token" field.
func (u *ClientSessionUpsert) SetToken(v string) *ClientSessionUpsert {
	u.Set(clientsession.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ClientSessionUpsert) UpdateToken() *ClientSessionUpsert {
	u.SetExcluded(clientsession.FieldToken)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ClientSessionUpsertOne) UpdateNewValues() *ClientSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ClientSessionUpsertOne) Ignore() *ClientSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClientSessionUpsertOne) DoNothing() *ClientSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClientSessionCreate.OnConflict
// documentation for more info.
func (u *ClientSessionUpsertOne) Update(set func(*ClientSessionUpsert)) *ClientSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClientSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *ClientSessionUpsertOne) SetToken(v string) *ClientSessionUpsertOne {
	return u.Update(func(s *ClientSessionUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ClientSessionUpsertOne) UpdateToken() *ClientSessionUpsertOne {
	return u.Update(func(s *ClientSessionUpsert) {
		s.UpdateToken()
	})
}

// Exec executes the query.
func (u *ClientSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClientSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClientSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ClientSessionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ClientSessionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ClientSessionCreateBulk is the builder for creating many ClientSession entities in bulk.
type ClientSessionCreateBulk struct {
	config
	err      error
	builders []*ClientSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the ClientSession entities in the database.
func (_c *ClientSessionCreateBulk) Save(ctx context.Context) ([]*ClientSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientSessionCreateBulk) SaveX(ctx context.Context) []*ClientSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ClientSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClientSessionUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ClientSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ClientSessionUpsertBulk {
	_c.conflict = opts
	return &ClientSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClientSessionCreateBulk) OnConflictColumns(columns ...string) *ClientSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClientSessionUpsertBulk{
		create: _c,
	}
}

// ClientSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of ClientSession nodes.
type ClientSessionUpsertBulk struct {
	create *ClientSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ClientSessionUpsertBulk) UpdateNewValues() *ClientSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ClientSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ClientSessionUpsertBulk) Ignore() *ClientSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClientSessionUpsertBulk) DoNothing() *ClientSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClientSessionCreateBulk.OnConflict
// documentation for more info.
func (u *ClientSessionUpsertBulk) Update(set func(*ClientSessionUpsert)) *ClientSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClientSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *ClientSessionUpsertBulk) SetToken(v string) *ClientSessionUpsertBulk {
	return u.Update(func(s *ClientSessionUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ClientSessionUpsertBulk) UpdateToken() *ClientSessionUpsertBulk {
	return u.Update(func(s *ClientSessionUpsert) {
		s.UpdateToken()
	})
}

// Exec executes the query.
func (u *ClientSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ClientSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClientSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClientSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
